### ISSUE TITLE
Multiple T500s not working correctly

### ISSUE THREAD

**Issue by NickYaVo2711** [jphalip/ticlib#1]
I am currently trying to program 2 stepper motors via 2 T500 boards. But I am having issues choosing which motor is supposed to run. While using the function "tic = TicUSB(None, '-SN-')" twice in a row with both SNs, basicly tic1 = SN1 and tic2 = SN2, the first object seems to get overwritten and the programmed movements are only beeing performed by one of the motors... . Do you have a solution or a workaround for this issue?
Have a great day
Nick

**Comment by jphalip** [comment]
Thanks for the report. I was able to reproduce this. I assume it might be a misuse of the pyusb library. I'll investigate.

**Comment by jphalip** [comment]
I think I found the bug. Could you try the fix in the `issue1` branch and let me know if that works for you?

**Comment by NickYaVo2711** [comment]
Thank you very much for your help. Both T500s now work flawless in the same program.

**Comment by jphalip** [comment]
Great to hear! Thanks for confirming. I'll release a new version with the fix.

**Comment by jphalip** [comment]
Fixed in 0.2.1
